[package]
name = "smolk8s"
description = "super small k8s setup"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = "4.5.8"
dialoguer = { version = "0.11.0", features = ["fuzzy-matcher", "fuzzy-select"] }
