name: cargo audit

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  cargo-deny:
    name: Run cargo deny
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1
